name: labofis
channels:
  - conda-forge
dependencies:
  - matplotlib
  - jupyter-book
  - jupyterlab
  - ipython
  - xarray
  - numpy
  - pandas
  - pre-commit
  - dask
  - pyproj
  - pythia-datasets
  - python
  - scipy
  - seaborn
  - cmocean
  - cartopy
  - nc-time-axis
  - netcdf4
  - h5netcdf
  - ffmpeg
  - python-graphviz
  - graphviz
  - setuptools>=69.0.3
  - sphinx-pythia-theme
  - pip
  - pip:
    - noaa_ftp
    - python-dateutil
    - copernicusmarine>=1.0<=2.0
  - python>=3.9,<3.12